### ISSUE TITLE
你好，请问你的电脑有出现usb硬盘意外退出的情况吗

### ISSUE THREAD

**Issue by WallfacerMajor** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#1]
首先很感谢你提供的efi,我这边尝试以后有一个问题。  

一个USB3.0的外置硬盘每隔一段时间后会弹出自动意外推出的提示。但是实际上去查看的时候还是可以正常访问。感觉是一推出后马上又自己连上了。  

你这边有类似的情况吗？

**Comment by xiaoMGitHub** [comment]
是不是你的外置设备的问题，我用 USB3.0的移动硬盘没有遇到过这种情况

**Comment by WallfacerMajor** [comment]
嗯，问题也不大，可以正常使用。
感觉我这边USB接口还是有一点小问题，使用外置的鼠标和键盘无法唤醒睡眠状态，但是使用自带的键盘是可以的。

**Comment by xiaoMGitHub** [comment]
@WallfacerMajor 好像 USB 外置设备是不能唤醒的，需要做相关的修改才行
