### ISSUE TITLE
what do i need to modify this if I don't use bcm cards？should i delete some kext or apci patch？

### ISSUE THREAD

**Issue by SINOPW** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#13]

**Comment by xiaoMGitHub** [comment]
@SINOPW You only need to remove AirportBrcmFixup_Release_v1.1.9.kext, BrcmFirmwareRepo_Release_v.2.2.10.kext, BrcmPatchRAM2_Release_v.2.2.10.kext, BT4LEContiunityFixup_Release_v1.1.2.kext

**Comment by SINOPW** [comment]
@xiaoMGitHub great,thanks
