### ISSUE TITLE
sound sometimes not working after installation v 2.0.0

### ISSUE THREAD

**Issue by Nurlan199206** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#14]
Hi.

i'm installed v 2.0.0 EFI.

touchpad is finally working, thank you. But sound sometimes not loading after boot.

![Снимок экрана 2019-05-06 в 20 02 49](https://user-images.githubusercontent.com/22808731/57230343-f8bb9300-7039-11e9-9454-d4e2c2788e2e.png)

**Comment by xiaoMGitHub** [comment]
@Nurlan199206 Try installing [ALCPlugFix](https://github.com/xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh/tree/master/ALCPlugFix)
