### ISSUE TITLE
what's the meaning of "Using Haswell MacBookAir6,2 until Clover has support for KabyLake identifiers"?why  choose  15,2 in  smbios?I  notice that the cpu  of  15,1 is 8750h.may it perform better or cause some matters?

### ISSUE THREAD

**Issue by SINOPW** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#16]

**Comment by xiaoMGitHub** [comment]
@SINOPW "Using Haswell MacBookAir6,2 until Clover has support for KabyLake identifiers"，This sentence has no meaning.At present, I have not found any difference between 15, 1 and 15, 2.

**Comment by SINOPW** [comment]
> @SINOPW "Using Haswell MacBookAir6,2 until Clover has support for KabyLake identifiers"，This sentence has no meaning.At present, I have not found any difference between 15, 1 and 15, 2.

thanks it's so kind of you.
