### ISSUE TITLE
How to disable the stock network card？there is some extra battery usage.btw I use usb network card instead.

### ISSUE THREAD

**Issue by SINOPW** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#17]

**Comment by xiaoMGitHub** [comment]
@SINOPW Can try using a hotpatch to disable.

**Comment by SINOPW** [comment]
> @SINOPW Can try using a hotpatch to disable.
can you lend me a hand.I tried to google but got nothing.and it's difficult to understand rehabman's hp hotpatch tutorial.

**Comment by xiaoMGitHub** [comment]
@SINOPW Reference this [[Guide] HackrNVMeFamily co-existence with IONVMeFamily using class-code spoof](https://www.tonymacx86.com/threads/guide-hackrnvmefamily-co-existence-with-ionvmefamily-using-class-code-spoof.210316/)
