### ISSUE TITLE
您好 我的設備是Y730 

### ISSUE THREAD

**Issue by k8602190** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#19]
我使用您的EFI (2.0.1) 大部分功能正常
也成功安裝MOJAVE 非常感謝
但是觸控板與聲卡無法使用
以及進入系統時會出現 busy timeout[0], (60s): 'TPAD'4次 才開機完成
我的聲卡是ALC298

**Comment by xiaoMGitHub** [comment]
@k8602190 你需要使用工具生成调试文件提供给我，[传送门](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/)，y530的声卡是ALC236，ALC298可用的id为3、11、13、21、22、28、29、30、47、66、72、99

**Comment by k8602190** [comment]
您好 這是我的生成結果 
[debug_96.zip](https://github.com/xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh/files/3214800/debug_96.zip)

**Comment by xiaoMGitHub** [comment]
@k8602190 你的触控板型号是SYNA7DB5，进入系统时出现busy timeout[0], (60s): 'TPAD'表明你需要修改DSDT来适应你的触控板，你可以根据该[指南](https://github.com/williambj1/VoodooI2C-PreRelease/blob/master/%E8%A7%A6%E6%91%B8%E6%9D%BF%E8%A1%A5%E5%85%85.md)来修复你的DSDT
