### ISSUE TITLE
您好，请问您的电脑在升级到10.14.3之后有出现经常性假死的情况么

### ISSUE THREAD

**Issue by KIDult226** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#2]
首先非常感谢您的EFI！
机型Y7000P i7+1060
我在用黑果小兵的EFI启动10.14.3的时候，除了UHD630无法驱动其他都基本正常，单指系统的正常运作
在换用你的EFI之后，尤其是升级到10.14.3之后，经常无缘无故卡死，只能重启解决问题；至今无法定位原因，我猜测是UHD630的驱动问题，因为在小兵的EFI上操作是相对正常的
修改：网卡换成了dw1830、USB接口自行用FB-Patcher驱动

**Comment by xiaoMGitHub** [comment]
@KIDult226 你应该是有装 i2c 触控板的驱动？

**Comment by KIDult226** [comment]
并没有另外加装任何驱动...只是现在经常性地出现系统使用中的panic，重启之后经常会出现启动过程中的timeout...

**Comment by KIDult226** [comment]
timeout过程包括不少驱动，几乎都试过...

**Comment by xiaoMGitHub** [comment]
@KIDult226 没有遇到你这种情况，群里的机友也没有反馈有类似的情况。我的EFI是添加了博通BCM94352z 无线网卡的驱动，如果你没有更换同款网卡可以尝试删除 AirportBrcmFixup_Release_v1.1.9.kext 、BrcmFirmwareData_Release_v.2.2.10.kext 、BrcmPatchRAM2_Release_v.2.2.10.kext.kext 这三个驱动后进行测试
