### ISSUE TITLE
你好，我用这个引导完成安装后启动项就消失了

### ISSUE THREAD

**Issue by Irisitomi** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#20]
按F3，可以显示恢复分区等，但是Windows引导和macOS引导都不见了

**Comment by xiaoMGitHub** [comment]
@Irisitomi 我需要Clover界面按F3界面和bios-boot页面的截图

**Comment by Irisitomi** [comment]
![IMG_20190526_105134](https://user-images.githubusercontent.com/45710811/58376788-02834700-7fa5-11e9-889c-8d411a2ef6dd.jpg)
![screenshot1](https://user-images.githubusercontent.com/45710811/58376836-09f72000-7fa6-11e9-9090-cd3c48bef290.png)
今天用U盘引导，能显示windows的，但是macOS的还是只有两个preboot和一个Recovery

**Comment by xiaoMGitHub** [comment]
@Irisitomi 明显是你启动了mac的文件保险箱功能，clover界面按F3，选择带有FileVault的启动项进去系统，然后关闭FileVault，当然不关闭也行，以后就选择带有FileVault的启动项启动就行了，不影响使用。

**Comment by Irisitomi** [comment]
好的，我回去试试，谢谢了
