### ISSUE TITLE
您好我的設備是y730

### ISSUE THREAD

**Issue by k8602190** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#21]
您好先感謝您之前的提點
我已經將ALC298 驅動 外放完美 但是接耳機音質不佳 想請問您如何解決
還有我的觸摸板也驅動了 支持手勢 但是處摸板按鍵無法使用
想請問您是如何驅動的

**Comment by k8602190** [comment]
Alc298接耳機雜音我已經解決了
還有我發現我的電池顯示無法更新都一直顯示100% 重開機才會改變
睡眠喚醒之後屏幕會一直突然花屏閃一下

**Comment by xiaoMGitHub** [comment]
@k8602190 或许你可以看看电池修补的相关指南。你是否开启了HiDPI？

**Comment by k8602190** [comment]
我已經開啟HIDPI依然會有這個問題 非常感謝您

**Comment by xiaoMGitHub** [comment]
@k8602190 我的意思是不建议开启HIDPI，开启只会带来更多的问题

**Comment by k8602190** [comment]
@xiaoMGitHub 我沒開啟HIDPI的時候更會閃 開啟之後好多了但是還是會閃屏
還有我筆記本上有雷電3的接口 但是網上很少資料能夠驅動 您的設備上是否也有 雷電3呢?如果有您能驅動嗎?

**Comment by xiaoMGitHub** [comment]
@xiaoMGitHub 我的笔记本属于中国大陆地区特供的产品，不支持雷电3

**Comment by xiaoMGitHub** [comment]
@k8602190 我的笔记本属于中国大陆地区特供的产品，不支持雷电3
