### ISSUE TITLE
你好,大佬,每次进入clover引导界面都会出现下面这些代码,是什么原因呀?谢谢!

### ISSUE THREAD

**Issue by tcgwl** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#22]
ApfsGptEntry is null.
Block device not supportedSuccess.
求指教,thanks!
![微信图片_20190606130708](https://user-images.githubusercontent.com/4530474/59008256-90401b80-885c-11e9-8b72-7d37739649c9.jpg)

**Comment by xiaoMGitHub** [comment]
@tcgwl 你的镜像问题吧，哪里下载的镜像？

**Comment by tcgwl** [comment]
黑锅小兵的镜像，已经改好了，换了一个ApfsDriverLoader-64.efi
