### ISSUE TITLE
如何屏蔽从盘pm981

### ISSUE THREAD

**Issue by RitualYang** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#26]

**Comment by xiaoMGitHub** [comment]
@RitualYang 编译[SSDT-DNVMe.dsl](https://github.com/xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh/blob/master/ACPI/hotpatch/SSDT-DNVMe.dsl)，然后放到ACPI/patched下面重启即可
