### ISSUE TITLE
现在pm981还是装不了吗

### ISSUE THREAD

**Issue by HXChow** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#27]
原固态是亿联128G的，想换个固态，顺带装一下黑果，得知想换成的981装不了
那除了981其他的固态
比如三星的970ep 英特尔的760p 西数黑盘 海康威视的C2000pro是不是都可以

**Comment by xiaoMGitHub** [comment]
@HXChow 联想定制的981基本是没希望的啦，强烈推荐Intel的760p，功耗低，不发热，群里大部分机友都换了这个固态，其他的nvme固态都发热严重

**Comment by HXChow** [comment]
> @HXChow 联想定制的981基本是没希望的啦，强烈推荐Intel的760p，功耗低，不发热，群里大部分机友都换了这个固态，其他的nvme固态都发热严重

那非联想定制的981呢，就是我是另外单独买的OEM版的981，不是自带的

**Comment by xiaoMGitHub** [comment]
> > @HXChow 联想定制的981基本是没希望的啦，强烈推荐Intel的760p，功耗低，不发热，群里大部分机友都换了这个固态，其他的nvme固态都发热严重
> 
> 那非联想定制的981呢，就是我是另外单独买的OEM版的981，不是自带的

零售版有解，OEM版基本是没戏

**Comment by HXChow** [comment]
> @HXChow 联想定制的981基本是没希望的啦，强烈推荐Intel的760p，功耗低，不发热，群里大部分机友都换了这个固态，其他的nvme固态都发热严重
> 
> 那非联想定制的981呢，就是我是另外单独买的OEM版的981，不是自带的
> 
> 零售版有解，OEM版基本是没戏

想了想还是入了海康的c2000pro，话说最新的981a（970ep的马甲）也无解?（没错，我就是不死心想买981a）

**Comment by xiaoMGitHub** [comment]
> > @HXChow 联想定制的981基本是没希望的啦，强烈推荐Intel的760p，功耗低，不发热，群里大部分机友都换了这个固态，其他的nvme固态都发热严重
> > 那非联想定制的981呢，就是我是另外单独买的OEM版的981，不是自带的
> > 零售版有解，OEM版基本是没戏
> 
> 想了想还是入了海康的c2000pro，话说最新的981a（970ep的马甲）也无解?（没错，我就是不死心想买981a）

带981的都不行，如果你真的要装黑苹果用的，我只推荐你买intel 760P

**Comment by HXChow** [comment]
> @HXChow 联想定制的981基本是没希望的啦，强烈推荐Intel的760p，功耗低，不发热，群里大部分机友都换了这个固态，其他的nvme固态都发热严重
> 那非联想定制的981呢，就是我是另外单独买的OEM版的981，不是自带的
> 零售版有解，OEM版基本是没戏
> 
> 想了想还是入了海康的c2000pro，话说最新的981a（970ep的马甲）也无解?（没错，我就是不死心想买981a）
> 
> 带981的都不行，如果你真的要装黑苹果用的，我只推荐你买intel 760P

好吧，谢谢你了
