### ISSUE TITLE
你好，您能帮忙做一个（CX20632）的AppleALC吗？

### ISSUE THREAD

**Issue by frankiezdh** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#28]
我在网上爬了不少文章，都没有成功。

这个[文件](https://pastebin.com/WFrY4nHv)是通过Ubuntu dump出来的Codec文件，请您帮忙。

谢谢。

**Comment by xiaoMGitHub** [comment]
@frankiezdh 你这个型号似乎AppleALC还没集成

**Comment by frankiezdh** [comment]
是的，没有集成。我想说，是您能帮忙根据codec做一个吗？我看了不少文章，但是都没做出来。

**Comment by xiaoMGitHub** [comment]
@frankiezdh 这个太麻烦了，你还是认真看看教程搞搞吧

**Comment by frankiezdh** [comment]
@xiaoMGitHub 好的，谢谢了。主要的问题是现在有的几个文档都写的云山雾罩，看不懂啊。我试着搞了一个，完全没有生效啊。

**Comment by xiaoMGitHub** [comment]
@frankiezdh 推荐黑果小兵博客的教程，说得挺详细的
