### ISSUE TITLE
你好，你的驱动方式和我的不一样，而且我无法使用，为什么？

### ISSUE THREAD

**Issue by hnie-xwz** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#4]
1. 昨天我测试了你的Clover，无法进入系统，启动过程中日志快速刷完然后重启了；
2. 我自己的其他驱动正常，但是蓝牙出现问题，第一次可以用，之后启动就找不到蓝牙设备了
3. 我使用的无线网卡驱动和你的同款。
4. 我使用**BCM94352z无线网卡**后，win10系统下的蓝牙驱动也失效了

**Comment by xiaoMGitHub** [comment]
@hnie-xwz 没理由不行的，群里150多号机友涵盖了y7000全系列的型号都是用我的EFI都没有不成功的。你是怎么测试我的EFI的？

**Comment by hnie-xwz** [comment]
@xiaoMGitHub 我的QQ是
673275656 可以的话，加我一下吧

**Comment by hnie-xwz** [comment]
在通过我的配置和你的配置相互切换启动的过程中，莫名其妙的可以启动成功了，我初步认为是系统缓存导致的，现在可以使用你的clover了，但是有个地方必须改
![修改的地方](http://ww1.sinaimg.cn/large/e8450fe4gy1g0jtct5iw5j20bl04b3yi.jpg)，这里的启动盘符改成我的安装盘名，如我的是**MacOs13_6**，所以就改成这个名字。
