### ISSUE TITLE
compatible Wifi card ?

### ISSUE THREAD

**Issue by bahhax404** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#6]
Hi great work I managed to install Macos on a y7000 using your files. 
only the trackpad(ELan) and wifi (intel ac-9560) are not working.
I want to replace the wifi card, with the one in the [link](https://www.ebay.de/itm/Broadcom-BCM94352Z-M-2-DELL-DW1560-802-11AC-867Mbps-Bluetooth-4-0-HACKINTOSH/113673407992?_trkparms=aid%3D555018%26algo%3DPL.SIM%26ao%3D2%26asc%3D20160323102634%26meid%3Da5ac51bc72a442b786a063d52e01c2ec%26pid%3D100623%26rk%3D1%26rkt%3D6%26sd%3D192852851838%26itm%3D113673407992&_trksid=p2047675.c100623.m-1), 
could you confirm if it is the right one before I order it, Thank you .
Link : [here](https://www.ebay.de/itm/Broadcom-BCM94352Z-M-2-DELL-DW1560-802-11AC-867Mbps-Bluetooth-4-0-HACKINTOSH/113673407992?_trkparms=aid%3D555018%26algo%3DPL.SIM%26ao%3D2%26asc%3D20160323102634%26meid%3Da5ac51bc72a442b786a063d52e01c2ec%26pid%3D100623%26rk%3D1%26rkt%3D6%26sd%3D192852851838%26itm%3D113673407992&_trksid=p2047675.c100623.m-1)

**Comment by xiaoMGitHub** [comment]
@bahhax404  The WiFi card (BCM94352Z ) you choose can be used normally.

**Comment by bahhax404** [comment]
Thank you I will order it. 
it was hard looking at all those form factors and connectors. I compared the Intel ac 9560 and BCM94352Z connector they re not the same. I guess all that matters is the M.2 type. I will have to read more on this.
thanks again for the confirmation.
