### ISSUE TITLE
Broadcom BCM94352z WLAN PCIE card (AKA: DW1560) -- is it support Lenovo?

### ISSUE THREAD

**Issue by phantuanphong** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#7]
Description :
Model: Broadcom BCM94352Z
Interface: NGFF(M.2)
Frequency band:2.4Ghz / 5Ghz
Speed:867Mbps
Network Standard : 802.11a/b/g/n/ac
Bluetooth 4.0
Support hackintosh/Mac(The driver for hackintosh/Mac need to be revised ,but we don’t have driver supply to you and tell you how to use on Mac.You must study by yourself, Pls check your computer system is  hackintosh/Mac or not before ordering this item. Thanks!)

**Pls note that it cannot support Lenovo/HP laptop!

==> Search on AliExpress and description show it "it cannot support Lenovo/HP laptop!"

**Comment by xiaoMGitHub** [comment]
@phantuanphong Y7000/Y530 does not have whitelist upon WLAN hardware,The dw1560 driver is already included in my EFI.

**Comment by phantuanphong** [comment]
Thanks you very much. 
I have a question. Can I use this card for Y530 because it cheap than BCM94352z? 

https://www.aliexpress.com/item/DW1820A-BCM94350ZAE-802-11ac-BT4-1-867Mbps-BCM94350-M-2-NGFF-WiFi-Wireless-Card-better-than/32632959564.html?spm=a2g0o.cart.0.0.7ea23c00aCHPQS

**Comment by xiaoMGitHub** [comment]
@phantuanphong It is not recommended to use dw1820A, this card has many problems for OSX

**Comment by phantuanphong** [comment]
Thanks you.
