### ISSUE TITLE
Problem with touchpad SYNA2846

### ISSUE THREAD

**Issue by phantuanphong** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#8]
I cant use left right button of touchpad, how to fix this problem. My touchpad model is SYNA2846

**Comment by xiaoMGitHub** [comment]
Check your touchpad settings.

**Comment by phantuanphong** [comment]
It mean left right physic button of touch pad

**Comment by xiaoMGitHub** [comment]
Unfortunately, physical button operations are not currently supported.

**Comment by phantuanphong** [comment]
Thanks you, i used Karabiner for map left mouse to keyboard
