### ISSUE TITLE
Audio Issue when wakeup from sleep mode

### ISSUE THREAD

**Issue by phantuanphong** [xiaoMGitHub/Lenovo_Y7000-Y530_Hackintosh#9]
Audio will noise when I wakeup PC from sleep. Maybe CodecCommander not load when wakeup.

**Comment by xiaoMGitHub** [comment]
Try installing CodecCommander to L/E.

**Comment by phantuanphong** [comment]
Not working

**Comment by xiaoMGitHub** [comment]
Have you installed alc_fix?

**Comment by phantuanphong** [comment]
I had fixef this problem by replug headphone
